controller_list:
  - name: effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    # allowed_execution_duration_scaling: 1.2
    # allowed_goal_duration_margin: 0.5
    # goal_time_tolerance: 0.6
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

